{
	"title": "fetching approvals. BL throw exception",
	"task": "sync",
	"taskData": {
		"type": "sync",
		"id": "sync-fail"
	},
	"steps": [
		{
			"func": "getBackendApprovals",
			"args": [
				{}
			],
			"output": []
		},
		{
			"func": "fetch",
			"args": [
				{
					"signatureList": []
				}
			],
			"exception": "CONNECTOR_ERROR"
		},
		{
			"func": "updateTask",
			"args": [
				"sync-fail",
				{
					"status": "InternalError",
					"meta": {
						"entity": "task",
						"taskType": "sync",
						"message": "Unexpected error: \"CONNECTOR_ERROR\""
					}
				}
			],
			"output": {}
		}
	]
}