{
	"title": "reject approval and failed in the BL when self validation is true",
	"task": "reject",
	"config": {
		"blConfig": {
			"selfValidation": true
		},
		"controllerConfig": {}
	},
	"taskData": {
		"type": "reject",
		"id": "taskId",
		"approval": "caprizaApproval.json"
	},
	"steps": [
		{
			"func": "getBackendApproval",
			"args": [
				{
					"id": "approvalId"
				}
			],
			"output": [
				"caprizaApproval.json"
			]
		},
		{
			"func": "reject",
			"args": [
				{
					"approval": "caprizaApproval.json"
				},
				{}
			],
			"exception": "CONNECTOR_ERROR"
		},
		{
			"func": "updateTask",
			"args": [
				"taskId",
				{
					"status": "InternalError",
					"meta": {
						"entity": "task",
						"taskType": "reject",
						"message": "Unexpected error: \"CONNECTOR_ERROR\""
					}
				}
			],
			"output": {}
		}
	]
}