{
  "title": "Sync using callback - 2 callbacks, send an error at the first callback",
  "task": "sync",
  "taskData": {
    "type": "sync",
    "id": "taskId"
  },
  "steps": [
    {
      "func": "getBackendApprovals",
      "args": [
        {}
      ],
      "output": []
    },
    {
      "func": "fetch",
      "args": [
        {
          "signatureList": []
        }
      ],
      "callback": [
        ["System Unavailable", { "approvals": ["rawApproval.json"] }, true],
        [null, { "approvals": ["rawmoreApproval.json"] }, false]],
      "outputType": "Result.Success",
      "output": {}
    },

    {
      "func": "sendApprovals",
      "args": [
        {
          "approvals": [
            "transformedmoreApproval.json"
          ],
          "rawApprovals": [
            "rawmoreApproval.json"
          ],
          "transformedApprovals": [
            "transformedmoreApproval.json"
          ]
        },
        {}
      ],
      "output": {}
    },
    {
      "func": "updateTask",
      "args": [
        "taskId",
        {
          "status": "InternalError",
          "meta": {
            "entity": "sdk",
            "message": "Unexpected error: \"System Unavailable\"",
            "taskType": "sync"
          }
        }
      ],
      "output": {}
    }
  ]
}